"""Generate an Axolotl QLoRA config from config/base.qlora.yaml + a family profile, so a
family is an ~8-line delta instead of a copy-pasted 90-line YAML. See docs/REFACTOR.md §3/§4."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

from coder_forge.family import REPO, load_profile

BASE = REPO / "config" / "base.qlora.yaml"
GENERATED_DIR = REPO / "config" / ".generated"


def render(family: str) -> Path:
    cfg = yaml.safe_load(BASE.read_text())
    profile = load_profile(family)
    train = profile["train"]
    lora = train["lora"]

    cfg["base_model"] = profile["base_model"]
    cfg["chat_template"] = profile.get("chat_template", "tokenizer_default")
    cfg["lora_r"] = lora["r"]
    cfg["lora_alpha"] = lora["alpha"]
    cfg["lora_target_modules"] = lora["target_modules"]
    cfg["sequence_len"] = train["sequence_len"]
    cfg["sample_packing"] = train["sample_packing"]
    cfg["pad_to_sequence_len"] = True
    cfg["learning_rate"] = train["learning_rate"]
    cfg["num_epochs"] = train["num_epochs"]
    cfg["seed"] = train["seed"]
    cfg["output_dir"] = profile["paths"]["output_dir"]
    cfg["dataset_prepared_path"] = profile["paths"]["dataset_prepared"]

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    out = GENERATED_DIR / f"{family}.yaml"
    header = (
        f"# GENERATED by `make config FAMILY={family}` from config/base.qlora.yaml +\n"
        f"# config/families/{family}.yaml — DO NOT EDIT. Edit the profile and regenerate.\n"
    )
    out.write_text(header + yaml.safe_dump(cfg, sort_keys=False))
    return out


def main(argv) -> None:
    family = argv[0] if argv else "qwen30"
    print(render(family))


if __name__ == "__main__":
    main(sys.argv[1:])
